ALTER TABLE `USER_TAB` DROP COLUMN `USER_TYPE`;

-- ----------------------------
-- Table structure for T_SYS_MENU
-- ----------------------------
DROP TABLE IF EXISTS `T_SYS_MENU`;
CREATE TABLE `T_SYS_MENU` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `P_ID` int(11) NOT NULL DEFAULT '0' COMMENT '父级主键',
  `MENU_NAME` varchar(100) NOT NULL COMMENT '菜单名称',
  `MENU_URL` varchar(200) DEFAULT '' COMMENT '菜单地址',
  `MENU_FETTLE` int(11) DEFAULT '1' COMMENT '菜单状态(1:启用，0:禁用)',
  `MENU_ICON` varchar(100) DEFAULT NULL COMMENT '菜单图标',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for T_SYS_ROLE
-- ----------------------------
DROP TABLE IF EXISTS `T_SYS_ROLE`;
CREATE TABLE `T_SYS_ROLE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_NAME` varchar(100) NOT NULL COMMENT '角色名称',
  `ROLE_FETTLE` int(11) DEFAULT '1' COMMENT '角色状态(1:启用，0:禁用)',
  `ROLE_CATEGORY` int(11) NOT NULL COMMENT '角色类别(1:普通角色，9999:超级管理员)',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for T_SYS_ROLE_MENU
-- ----------------------------
DROP TABLE IF EXISTS `T_SYS_ROLE_MENU`;
CREATE TABLE `T_SYS_ROLE_MENU` (
  `R_ID` int(11) NOT NULL COMMENT '角色ID',
  `M_ID` int(11) NOT NULL COMMENT '菜单ID',
  PRIMARY KEY (`R_ID`,`M_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 更新用户为普通用户
UPDATE managing_users_tab SET user_type = 2;

-- 企业表
DROP TABLE IF EXISTS `T_COMPANY`;
CREATE TABLE `T_COMPANY` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `COMPANY_NAME` VARCHAR(100) NOT NULL COMMENT '企业名称',
  `COMPANY_CODE` VARCHAR(100) NOT NULL COMMENT '企业组织机构代码',
  `LICENSE_PATH` VARCHAR(255) NOT NULL COMMENT '营业执照',
  `FETTLE` INT(11) DEFAULT 1 COMMENT '状态(1:注册未认证,2:已认证,3:禁用)',
  `SIGN_FETTLE` INT(11) DEFAULT 0 COMMENT '电子签收开通状态(0:未开通,1:已开通)',
  `SIGN_USER_ID` INT(11) DEFAULT NULL COMMENT '电子签收开通人',
  `SIGN_TIME` DATETIME DEFAULT NULL COMMENT '电子签收开通时间',
  `USER_ID` INT(11) NOT NULL COMMENT '创建人',
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NOW() COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `U_KEY_COMPANY_NAME` (`COMPANY_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 公章
DROP TABLE IF EXISTS `T_COMPANY_SEAL`;
CREATE TABLE `T_COMPANY_SEAL` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `COMPANY_ID` BIGINT(20) NOT NULL COMMENT '企业编号',
  `SEAL_DATA` TEXT NOT NULL COMMENT '印章数据,图片BASE64数据',
  `FETTLE` INT(11) DEFAULT 1 COMMENT '状态(1:可用,2:禁用)',
  `USER_ID` INT(11) NOT NULL COMMENT '创建人',
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NOW() COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 企业电子回单模板
DROP TABLE IF EXISTS `T_COMPANY_TEMPLATE`;
CREATE TABLE `T_COMPANY_TEMPLATE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `COMPANY_ID` BIGINT(20) NOT NULL COMMENT '企业编号',
  `CSS_STRING` TEXT NOT NULL COMMENT '模板样式,BASE64数据',
  `HTML_STRING` TEXT NOT NULL COMMENT '模板HTML,BASE64数据',
  `USER_ID` INT(11) NOT NULL COMMENT '创建人',
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NOW() COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 用户认证信息
DROP TABLE IF EXISTS `T_USER_LEGALIZE`;
CREATE TABLE `T_USER_LEGALIZE` (
  `ID` INT(11) NOT NULL COMMENT '用户编号',
  `EMPLOYEE_NAME` VARCHAR(20) NOT NULL COMMENT '员工名称',
  `MOBILE_PHONE` VARCHAR(11) NOT NULL COMMENT '手机号',
  `ID_CARD_NO` VARCHAR(20) NOT NULL COMMENT '身份证号码',
  `LEGALIZE_TIME` DATETIME DEFAULT NOW() COMMENT '认证时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 企业-员工信息
DROP TABLE IF EXISTS `T_COMPANY_EMPLOYEE`;
CREATE TABLE `T_COMPANY_EMPLOYEE` (
  `COMPANY_ID` BIGINT(20) NOT NULL COMMENT '企业编号',
  `EMPLOYEE_ID` INT(11) NOT NULL COMMENT '用户编号',
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '添加时间',
  `authorize_seal_id` BIGINT(20) DEFAULT NULL COMMENT '授权公章编号',
  `AUTHORIZE_FILE` VARCHAR(500) DEFAULT NULL COMMENT '授权书路径',
  `AUTHORIZE_TIME` DATETIME DEFAULT NULL COMMENT '授权时间',
  `USER_ID` INT(11) NOT NULL COMMENT '操作人',
  PRIMARY KEY (`COMPANY_ID`, `EMPLOYEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 消息通知
DROP TABLE IF EXISTS `T_MESSAGE`;
CREATE TABLE `T_MESSAGE` (
  `ID` BIGINT(20) NOT NULL COMMENT '消息编号',
  `MSG_TITLE` VARCHAR(50) NOT NULL COMMENT '消息头',
  `MSG_CONTEXT` VARCHAR(200)  NOT NULL COMMENT '消息内容',
  `MSG_TYPE` INT(2) DEFAULT 1 COMMENT '消息类型(1:系统消息)',
  `USER_ID` INT(11) NOT NULL COMMENT '接收者用户编号',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '发送时间',
  `ADJUNCT` VARCHAR(100) DEFAULT NULL COMMENT '附件',
  PRIMARY KEY (`ID`),
  INDEX `INDEX_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 订单
DROP TABLE IF EXISTS `T_ORDER`;
CREATE TABLE `T_ORDER` (
  `ID` BIGINT(20) NOT NULL COMMENT '订单编号',
  `ORDER_NO` VARCHAR(50) DEFAULT NULL COMMENT '客户订单编号',
  `DELIVERY_NO` VARCHAR(50) NOT NULL COMMENT '配送单号',
  `SHIPPER_ID` BIGINT(20) NOT NULL COMMENT '发货方编号',
  `RECEIVE_ID` BIGINT(20) NOT NULL COMMENT '收货方编号',
  `CONVEY_ID` BIGINT(20) NOT NULL COMMENT '承运方编号',
  `RECEIVER_NAME` VARCHAR(30)  NOT NULL COMMENT '收货人',
  `RECEIVER_CONTACT` VARCHAR(100) DEFAULT 1 COMMENT '联系方式',
  `RECEIVE_ADDRESS` VARCHAR(255) NOT NULL COMMENT '收货地址',
  `FETTLE` INT(4) DEFAULT 0 COMMENT '订单状态(0:默认, 1:待签收, 2:签收中, 3:异常签收, 99:作废)',
  `RECEIPT_FETTLE` INT(4) DEFAULT 0 COMMENT '回单状态(0:未生成电子回单,1:已生成电子回单,2:收货方已签收承运商未签收,3:承运商已签收发货方未签收,4:收货方承运商都已经签收,5:签收完成)',
  `DELIVERY_TIME` DATETIME DEFAULT NULL COMMENT '发货时间',
  `RECEIVE_TIME` DATETIME DEFAULT NULL COMMENT '到货时间',
  `REMARK` VARCHAR(200) DEFAULT NULL COMMENT '备注',
  `CREATE_USER_ID` INT(11) NOT NULL COMMENT '创建人',
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NOW() COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 订单电子回单
DROP TABLE IF EXISTS `T_ORDER_RECEIPT`;
CREATE TABLE `T_ORDER_RECEIPT` (
  `ORDER_NO` BIGINT(20) NOT NULL COMMENT '订单编号',
  `PDF_PATH` VARCHAR(100) NOT NULL COMMENT '电子回单存储路径',
  `USER_ID` INT(11) NOT NULL COMMENT '创建人',
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NOW() COMMENT '更新时间',
  PRIMARY KEY (`ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 订单异常
DROP TABLE IF EXISTS `T_ORDER_EXCEPTION`;
CREATE TABLE `T_ORDER_EXCEPTION` (
  `ORDER_NO` BIGINT(20) NOT NULL COMMENT '订单编号',
  `CONTENT` VARCHAR(500) NOT NULL COMMENT '电子回单存储路径',
  `USER_ID` INT(11) NOT NULL COMMENT '创建人',
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NOW() COMMENT '更新时间',
  PRIMARY KEY (`ORDER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 订单明细
DROP TABLE IF EXISTS `T_ORDER_COMMODITY`;
CREATE TABLE `T_ORDER_COMMODITY` (
  `ID` BIGINT(20) NOT NULL COMMENT '订单明细编号',
  `ORDER_ID` BIGINT(20) NOT NULL COMMENT '订单编号',
  `COMMODITY_NO` VARCHAR(30) DEFAULT NULL COMMENT '物料编号',
  `COMMODITY_NAME` VARCHAR(100) DEFAULT NULL COMMENT '物料名称',
  `COMMODITY_TYPE` VARCHAR(100) DEFAULT NULL COMMENT '物料型号',
  `COMMODITY_UNIT` VARCHAR(20) DEFAULT NULL COMMENT '物料单位',
  `QUANTITY` INT(4) DEFAULT 0 COMMENT '数量(件)',
  `BOX_COUNT` INT(4) DEFAULT 0 COMMENT '箱数(箱)',
  `VOLUME` DOUBLE DEFAULT 0 COMMENT '体积(立方米)',
  `WEIGHT` DOUBLE DEFAULT 0 COMMENT '重量(千克)',
  `REMARK` VARCHAR(200) DEFAULT NULL COMMENT '备注',
  `CREATE_USER_ID` INT(11) NOT NULL COMMENT '创建人',
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NOW() COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  INDEX `INDEX_ORDER_ID` (`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 订单签章
DROP TABLE IF EXISTS `T_ORDER_SIGNATURE`;
CREATE TABLE `T_ORDER_SIGNATURE` (
  `ID` BIGINT(20) NOT NULL COMMENT '订单明细编号',
  `ORDER_ID` BIGINT(20) NOT NULL COMMENT '订单编号',
  `SIGN_ROLE` INT(4) NOT NULL COMMENT '签章角色(1:发货方、2:承运商、3:收货方)',
  `COMPANY_ID` BIGINT(20) NOT NULL COMMENT '签章公司编号',
  `USER_ID` INT(11) NOT NULL COMMENT '签章人',
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间',
  `SEAL_ID` BIGINT(20) NOT NULL COMMENT '公章',
  PRIMARY KEY (`ID`),
  INDEX `INDEX_ORDER_ID` (`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;





-- ----------------------------
-- 茅台打印相关
-- ----------------------------
-- ----------------------------
-- Table structure for MOUTAI_CONVEY
-- ----------------------------
DROP TABLE IF EXISTS `MOUTAI_CONVEY`;
CREATE TABLE `MOUTAI_CONVEY` (
  `ID` bigint(20) NOT NULL COMMENT '编号',
  `CONVEY_NAME` varchar(255) NOT NULL COMMENT '承运单位名称',
  `CREATE_USER_ID` INT(11) NOT NULL COMMENT '创建人',
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for MOUTAI_CUSTOMER
-- ----------------------------
DROP TABLE IF EXISTS `MOUTAI_CUSTOMER`;
CREATE TABLE `MOUTAI_CUSTOMER` (
  `CUSTOMER_NO` varchar(100) NOT NULL COMMENT '客户编码',
  `CUSTOMER_NAME` varchar(200) NOT NULL COMMENT '客户名称',
  `PROVINCE` varchar(50) NOT NULL COMMENT '省',
  `CITY` varchar(60) NOT NULL COMMENT '市',
  `ADDRESS` varchar(255) NOT NULL COMMENT '详细地址',
  `CONTACT_NAME` varchar(50) NOT NULL COMMENT '联系人',
  `CONTACT_PHONE` varchar(30) DEFAULT NULL COMMENT '联系电话',
  `FAX` varchar(30) DEFAULT NULL COMMENT '传真',
  `CREATE_USER_ID` INT(11) NOT NULL COMMENT '创建人',
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间',
  PRIMARY KEY (`CUSTOMER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for MOUTAI_ORDER
-- ----------------------------
DROP TABLE IF EXISTS `MOUTAI_ORDER`;
CREATE TABLE `MOUTAI_ORDER` (
  `ID` bigint(20) NOT NULL COMMENT '编号(发货编号)',
  `SCHEDULE_NO` varchar(20) DEFAULT NULL COMMENT '调拨编号',
  `CUSTOMER_NO` varchar(100) NOT NULL COMMENT '客户编号',
  `STORE_ID` int(11) DEFAULT NULL COMMENT '仓库编号',
  `CONVEY_ID` bigint(20) DEFAULT NULL COMMENT '承运单位编号',
  `SPECIFICATION` varchar(255) DEFAULT NULL COMMENT '规格',
  `BOTTLES` int(11) DEFAULT '0' COMMENT '瓶数',
  `QUANTITY` int(11) DEFAULT '0' COMMENT '件数',
  `BUY_ORG` varchar(255) DEFAULT NULL COMMENT '购货人',
  `CREATE_USER_ID` int(11) NOT NULL COMMENT '创建人',
  `CREATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `PRINT_SIGN` int(11) DEFAULT '0' COMMENT '是否打印过',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for MOUTAI_TAKER
-- ----------------------------
DROP TABLE IF EXISTS `MOUTAI_TAKER`;
CREATE TABLE `MOUTAI_TAKER` (
  `ID` bigint(20) NOT NULL COMMENT '编号',
  `CONVEY_ID` bigint(20) NOT NULL COMMENT '所属单位',
  `TAKE_NAME` varchar(100) NOT NULL COMMENT '取单人名称',
  `TAKE_PHONE` varchar(30) NOT NULL COMMENT '取单人联系电话',
  `TAKE_IDCARE` varchar(20) NOT NULL COMMENT '取单人身份证号码',
  `FETTLE` int(2) NOT NULL DEFAULT '1' COMMENT '状态',
  `CREATE_USER_ID` INT(11) NOT NULL COMMENT '创建人',
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `driver_container_tab` ADD `receiver_name` varchar(255) DEFAULT NULL COMMENT '收货客户';
UPDATE
  driver_container_tab d , waybill_tab w
SET
  d.receiver_name = w.receiver_name
WHERE
  d.barcode = w.barcode;