INSERT INTO `T_SYS_MENU` (`ID`, `P_ID`, `MENU_NAME`, `MENU_URL`, `MENU_FETTLE`, `MENU_ICON`, `MENU_TYPE`) VALUES ('56', '39', '发货管理', 'enterprise/backstage/view/shippermanage', '1', NULL, '1');
INSERT INTO `T_SYS_MENU` (`ID`, `P_ID`, `MENU_NAME`, `MENU_URL`, `MENU_FETTLE`, `MENU_ICON`, `MENU_TYPE`) VALUES ('57', '0', '客户管理', '', '1', NULL, '1');
INSERT INTO `T_SYS_MENU` (`ID`, `P_ID`, `MENU_NAME`, `MENU_URL`, `MENU_FETTLE`, `MENU_ICON`, `MENU_TYPE`) VALUES ('58', '57', '客户管理', 'enterprise/customer/view/manage', '1', NULL, NULL);

INSERT INTO `T_SYS_ROLE_MENU` (`R_ID`, `M_ID`) VALUES ('4', '56');
INSERT INTO `T_SYS_ROLE_MENU` (`R_ID`, `M_ID`) VALUES ('4', '57');
INSERT INTO `T_SYS_ROLE_MENU` (`R_ID`, `M_ID`) VALUES ('4', '58');


-- 企业客户关系
DROP TABLE IF EXISTS `T_COMPANY_CUSTOMER`;
CREATE TABLE `T_COMPANY_CUSTOMER` (
  `KEY`  BIGINT(20) NOT NULL COMMENT '编号' ,
  `NAME`  VARCHAR(50) NOT NULL COMMENT '客户名称' ,
  `OWNER_KEY`  BIGINT(20) NOT NULL COMMENT '所属企业编号' ,
  `COMPANY_KEY`  BIGINT(20) DEFAULT 0 COMMENT '对应的企业编号' ,
  `USER_KEY` INT(11) NOT NULL COMMENT '创建人' ,
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间' ,
  `UPDATE_TIME` DATETIME DEFAULT NOW() COMMENT '更新时间' ,
  `STATUS` INT NULL COMMENT '是否启用' ,
  PRIMARY KEY (`KEY`),
  INDEX INDEX_COMPANY_KEY (`COMPANY_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '企业客户关系';


ALTER TABLE `T_ORDER` ADD COLUMN `CLIENT_TYPE` INT(4) DEFAULT 1  COMMENT '收货方类型(1:企业,2:客户关系)';
ALTER TABLE `T_ORDER_INVALID` ADD COLUMN `CLIENT_TYPE` INT(4) DEFAULT 1  COMMENT '收货方类型(1:企业,2:客户关系)';


-- 用户资源
DROP TABLE IF EXISTS `T_USER_RESOURCE`;
CREATE TABLE `T_USER_RESOURCE` (
  `USER_ID`  INT(11) NOT NULL COMMENT '用户编号' ,
  `INTEGRAL`  BIGINT(20) DEFAULT 0 COMMENT '积分' ,
  `MONEY`  BIGINT(20) DEFAULT 0 COMMENT '金额',
  PRIMARY KEY (`USER_ID`),
  INDEX INDEX_USER_ID (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户资源';

-- 资源变更明细
DROP TABLE IF EXISTS `T_RESOURCE_CHANGE`;
CREATE TABLE `T_RESOURCE_CHANGE` (
  `CHANGE_ID`  BIGINT(20) NOT NULL COMMENT '变更流水号' ,
  `USER_ID`  INT(11) NOT NULL COMMENT '用户编号' ,
  `RES_TYPE` INT(11) DEFAULT 0 COMMENT '资源类型(1:红包, 2:积分)' ,
  `CHANGE_CAUSE`  INT(11) DEFAULT 0 COMMENT '变更原因(1:抽奖活动,2:提现)',
  `CHANGE_VALUE`  BIGINT(20) DEFAULT 0 COMMENT '变更数值(正数为新增,负数便是减少)',
  `CHANGE_TIME`  DATETIME DEFAULT NOW() COMMENT '变更时间',
  PRIMARY KEY (`CHANGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '资源变更明细';

-- 抽奖记录
DROP TABLE IF EXISTS `T_LOTTERY_NOTE`;
CREATE TABLE `T_LOTTERY_NOTE` (
  `NOTE_ID`  VARCHAR(50) NOT NULL COMMENT '流水号' ,
  `USER_ID`  INT(11) NOT NULL COMMENT '用户编号' ,
  `LOTTERY_TYPE` INT(11) DEFAULT 0 COMMENT '抽奖事件(装车上报, 扫码上报...)' ,
  `OBJECT_KEY` VARCHAR(30) DEFAULT NULL COMMENT '其他编号' ,
  `AWARD_TYPE`  INT(11) DEFAULT 0 COMMENT '奖励类型(1:红包,2:积分,3:其他)',
  `AWARD_VALUE`  BIGINT(20) DEFAULT 0 COMMENT '奖励数值',
  `CREATE_TIME`  DATETIME DEFAULT NOW() COMMENT '创建时间',
  `MODIFY_TIME`  DATETIME DEFAULT NOW() COMMENT '更新时间时间',
  PRIMARY KEY (`NOTE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '抽奖记录';

-- 提现
DROP TABLE IF EXISTS `T_MONEY_EXTRACT`;
CREATE TABLE `T_MONEY_EXTRACT` (
  `EXTRACT_ID`  VARCHAR(50) NOT NULL COMMENT '流水号' ,
  `USER_ID`  INT(11) NOT NULL COMMENT '用户编号' ,
  `EXTRACT_VALUE`  BIGINT(20) DEFAULT 0 COMMENT '提取数值',
  `HANDLE_TYPE`  INT(11) DEFAULT 0 COMMENT '处理类型(0:申请，1:申请拒绝，2:申请通过)',
  `APPLY_TIME`  DATETIME DEFAULT NOW() COMMENT '申请时间',
  `HANDLE_TIME`  DATETIME DEFAULT NOW() COMMENT '处理时间',
  PRIMARY KEY (`EXTRACT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '提现';
