
-- 签署第三方关联表
DROP TABLE IF EXISTS `T_SIGN_ASSOCIATE`;
CREATE TABLE `T_SIGN_ASSOCIATE` (
  `OBJECT_TYPE` VARCHAR(50) NOT NULL COMMENT '对象类型',
  `OBJECT_KEY` VARCHAR(20) NOT NULL COMMENT '对象编号',
  `THIRD_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '第三方类型',
  `THIRD_OBJECT_KEY` VARCHAR(50) NOT NULL COMMENT '第三方对象编号',
  `OPERATE_ID` INT(11) NOT NULL COMMENT '操作人',
  `OPERATE_TIME` DATETIME DEFAULT NOW() COMMENT '操作编号',
  PRIMARY KEY (`OBJECT_TYPE`, `OBJECT_KEY`, `THIRD_TYPE`, `THIRD_OBJECT_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--公司印章表

ALTER TABLE `T_COMPANY_SEAL` ADD COLUMN `COMPANY_NAME` varchar(50) DEFAULT NULL  COMMENT '企业简称';
ALTER TABLE `T_COMPANY_SEAL` ADD COLUMN `SEAL_TYPE` varchar(10) DEFAULT NULL  COMMENT '印章样式';
ALTER TABLE `T_COMPANY_SEAL` ADD COLUMN `COPYWRITING` varchar(50) DEFAULT NULL  COMMENT '横向文案';
ALTER TABLE `T_COMPANY_SEAL` ADD COLUMN `SECURITY_CODE` varchar(50) DEFAULT NULL  COMMENT '防伪码信息';

--实名认证表

ALTER TABLE `T_USER_LEGALIZE` ADD COLUMN `SEAL_TYPE` varchar(10) DEFAULT NULL  COMMENT '印章样式';
ALTER TABLE `T_USER_LEGALIZE` ADD COLUMN `SIGNATURE_IMG_URL` varchar(255) DEFAULT NULL  COMMENT '手绘签名图片地址';



-- 订单的纸质回单
DROP TABLE IF EXISTS `T_PAPER_RECEIPT`;
CREATE TABLE `T_PAPER_RECEIPT` (
  `ID`  BIGINT(20) NOT NULL COMMENT '编号' ,
  `ORDER_KEY`  BIGINT(20) NOT NULL COMMENT '订单编号' ,
  `USER_ID`  INT(11) NOT NULL COMMENT '创建人' ,
  `CREATE_TIME`  DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
  `RECEIPT_COUNT` INT(11) DEFAULT 0 COMMENT '回单图片数量' ,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 订单的操作记录里新增操作人编号
ALTER TABLE `T_OPERATE_NOTE` ADD COLUMN `USER_KEY` INT(11) DEFAULT NULL  COMMENT '记录人编号';

--订单表添加回单是否上传状态
ALTER TABLE `T_ORDER` ADD COLUMN `IS_RECEIPT` INT(10) DEFAULT '0' COMMENT '是否上传回单(0:否,大于0:是)';
ALTER TABLE `T_ORDER` CHANGE `RECEIPT_FETTLE` `SIGN_FETTLE` INT(10) DEFAULT 0 COMMENT '签收状态(0:未签收,1:正常签收,2:异常签收)';
ALTER TABLE `T_ORDER_INVALID` ADD COLUMN `IS_RECEIPT` INT(10) DEFAULT '0' COMMENT '是否上传回单(0:否,大于0:是)';
ALTER TABLE `T_ORDER_INVALID` CHANGE `RECEIPT_FETTLE` `SIGN_FETTLE` INT(10) DEFAULT 0 COMMENT '签收状态(0:未签收,1:正常签收,2:异常签收)';
ALTER TABLE `T_ORDER_RECEIPT` ADD COLUMN `FETTLE` INT(10) DEFAULT '0' COMMENT '回单状态(0:未生成电子回单;1:已生成电子回单;2:收货方已签;3:承运商已签;4:双方都已签)';

ALTER TABLE `user_tab` ADD COLUMN `head_img` VARCHAR(200) DEFAULT NULL COMMENT '用户微信头像';

-- 签署方管理
CREATE TABLE `T_SIGNED_RELATION` (
  `ID` bigint(20) NOT NULL COMMENT '编号',
  `CREATE_ID` int(11) NOT NULL COMMENT '创建人',
  `COMPANY_NAME` varchar(30) NOT NULL COMMENT '发货方公司',
  `SIGN_COMPANY_NAME` varchar(30) NOT NULL COMMENT '签署方公司',
  `CREATETIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATETIME` datetime DEFAULT NULL COMMENT '修改时间',
  `STARTTIME` datetime NOT NULL COMMENT '签收开始时间',
  `ENDTIME` datetime NOT NULL COMMENT '签收结束时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `T_SIGN_RECORD` (
  `ID` bigint(20) NOT NULL COMMENT '编号',
  `RELATION_ID` bigint(20) NOT NULL COMMENT '签署关系编号',
  `CREATETIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `STARTTIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '签收开始时间',
  `ENDTIME` datetime DEFAULT NULL COMMENT '签收结束时间',
  `SIGEN_COUNT` int(11) DEFAULT NULL COMMENT '累计签收份数',
  `MODIFY_ID` int(11) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `T_EMPLOYEE_SEAL`;
CREATE TABLE `T_EMPLOYEE_SEAL` (
  `ID` bigint(20) NOT NULL,
  `COMPANY_ID` bigint(20) NOT NULL COMMENT '企业编号',
  `EMPLOYEE_ID` int(11) NOT NULL COMMENT '用户编号',
  `AUTHORIZE_SEAL_ID` bigint(20) DEFAULT NULL COMMENT '授权公章编号',
  `AUTHORIZE_TIME` datetime DEFAULT NULL COMMENT '授权时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

