-- 不更新
-- -----------------------------------------------------------------------------------------------------
-- DELETE FROM `sys_request_serial`;
ALTER TABLE `sys_request_serial` ADD COLUMN `content_type` varchar(100) DEFAULT NULL  COMMENT '数据格式';
ALTER TABLE `sys_request_serial` ADD COLUMN `class_name` varchar(100) DEFAULT NULL  COMMENT '类名';
ALTER TABLE `sys_request_serial` ADD COLUMN `signature` varchar(30) DEFAULT NULL  COMMENT '方法';
ALTER TABLE `sys_request_serial` ADD COLUMN `args` varchar(300) DEFAULT NULL  COMMENT '参数';
ALTER TABLE `sys_request_serial` ADD COLUMN `exception` varchar(100) DEFAULT NULL  COMMENT '异常';
ALTER TABLE `sys_request_serial` ADD COLUMN `session_key` varchar(100) DEFAULT NULL  COMMENT '会话标识';
ALTER TABLE `sys_request_serial` ADD COLUMN `return_value` varchar(100) DEFAULT NULL  COMMENT '返回值';

-- 对外接口配置
DROP TABLE IF EXISTS `T_ADVENTIVE`;
CREATE TABLE `T_ADVENTIVE` (
  `ACCESS_KEY`  BIGINT(20) NOT NULL COMMENT '编号' ,
  `PUBLIC_KEY`  VARCHAR(200) NOT NULL COMMENT '公钥' ,
  `PRIVATE_KEY`  VARCHAR(300) NOT NULL COMMENT '私钥' ,
  `WHITE_LIST`  VARCHAR(200) DEFAULT NULL COMMENT 'IP白名单' ,
  `HIS_CODE`  VARCHAR(20) NOT NULL COMMENT '推送对象代码' ,
  `FREQUENCY`  INT(10) DEFAULT 1 COMMENT '推送频率(秒/次)' ,
  `FREQUENCY_TYPE` INT(10) DEFAULT 1 COMMENT '频率类型(1:正常,2:递增,前三次相同,之后频率越来越慢)' ,
  `MAX_TIMES` INT(10) DEFAULT 10 COMMENT '同一条记录最大推送次数' ,
  `LAST_TIME` DATETIME DEFAULT NOW() COMMENT '最后一次推送的时间' ,
  `FETTLE` INT(11) DEFAULT 1 COMMENT '状态(1:可用,2:不可用)' ,
  `DELIVERY_URL` VARCHAR(300) DEFAULT NULL COMMENT '数据推送URL' ,
  PRIMARY KEY (`ACCESS_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 对外推送记录
DROP TABLE IF EXISTS `T_ADVENTIVE_PUSH`;
CREATE TABLE `T_ADVENTIVE_PUSH` (
  `ADVENTIVE_ID` BIGINT(20) NOT NULL COMMENT '推送对象' ,
  `INCLUDES`  VARCHAR(500) DEFAULT NULL COMMENT '要推送的配置(S发货方编号#R收货方编号#C承运方编号)' ,
  `EXCLUDES`  VARCHAR(500) DEFAULT NULL COMMENT '不推送的配置(S发货方编号#R收货方编号#C承运方编号)' ,
  PRIMARY KEY (`ADVENTIVE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 对外推送记录
DROP TABLE IF EXISTS `T_ADVENTIVE_NOTE`;
CREATE TABLE `T_ADVENTIVE_NOTE` (
  `ID` BIGINT(20) NOT NULL COMMENT '编号' ,
  `ADVENTIVE_ID` BIGINT(20) NOT NULL COMMENT '推送对象' ,
  `NOTE_TYPE`  VARCHAR(10) NOT NULL COMMENT '记录类型' ,
  `OBJECT_KEY`  VARCHAR(100) NOT NULL COMMENT '推送的数据编号' ,
  `LAST_TIME`  DATETIME DEFAULT NOW() COMMENT '最后一次推送的时间' ,
  `REMARK`  VARCHAR(200) DEFAULT NULL COMMENT '备注' ,
  `FETTLE` INT(11) DEFAULT 0 COMMENT '状态(0:等待处理,1:处理中,2:处理成功,99:放弃处理)' ,
  `COUNT` INT(11) DEFAULT 0 COMMENT '处理次数' ,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 签署记录新增个人印章编号字段
ALTER TABLE `T_ORDER_SIGNATURE` ADD COLUMN `PERSONAL_SEAL` BIGINT(20) NOT NULL COMMENT '个人印章编号';


-- 个人印章--
DROP TABLE IF EXISTS `T_PERSONAL_SEAL`;
CREATE TABLE `T_PERSONAL_SEAL` (
  `ID` bigint(20) NOT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `SEAL_STYLE` varchar(10) NOT NULL,
  `SEAL_IMG_PATH` varchar(255) DEFAULT NULL,
  `SEAL_TYPE` int(11) NOT NULL COMMENT '印章类型 1:印章类型  2：手写签名',
  `CREATE_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 个人/公司印章关联表--
DROP TABLE IF EXISTS `T_EMPLOYEE_SEAL`;
CREATE TABLE `T_EMPLOYEE_SEAL` (
  `ID` bigint(20) NOT NULL,
  `COMPANY_ID` bigint(20) NOT NULL COMMENT '企业编号',
  `EMPLOYEE_ID` int(11) NOT NULL COMMENT '用户编号',
  `AUTHORIZE_SEAL_ID` bigint(20) DEFAULT NULL COMMENT '授权公章编号',
  `AUTHORIZE_TIME` datetime DEFAULT NULL COMMENT '授权时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



ALTER TABLE T_USER_LEGALIZE DROP COLUMN SEAL_TYPE;
ALTER TABLE T_USER_LEGALIZE DROP COLUMN SIGNATURE_IMG_URL;