-- 模板字段
DROP TABLE IF EXISTS `T_TEMPLATE_PROPERTY`;
CREATE TABLE `T_TEMPLATE_PROPERTY` (
  `KEY`  BIGINT(20) NOT NULL COMMENT '字段编号' ,
  `NAME`  VARCHAR(50) NOT NULL COMMENT '字段名称' ,
  `DESCRIPTION`  VARCHAR(100) DEFAULT NULL COMMENT '字段描述' ,
  `CLASS_NAME`  VARCHAR(60) DEFAULT NULL COMMENT '字段所属类' ,
  `DATA_KEY`  VARCHAR(30) NOT NULL COMMENT '字段属性名' ,
  `DATA_TYPE`  INT(2) DEFAULT 1 COMMENT '字段数据类型(1:字符串,2:整数,3:小数,4:日期)' ,
  `TYPE`  INT(2) DEFAULT 2 COMMENT '字段类型(1:必填,2:选填)',
  PRIMARY KEY (`KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '模板字段';

-- 企业订单导入模板
DROP TABLE IF EXISTS `T_IMPORT_TEMPLATE`;
CREATE TABLE `T_IMPORT_TEMPLATE` (
  `KEY`  BIGINT(20) NOT NULL COMMENT '模板编号' ,
  `COMPANY_KEY` BIGINT(20) NOT NULL COMMENT '企业编号' ,
  `NAME`  VARCHAR(100) NOT NULL COMMENT '模板名称' ,
  `FETTLE`  INT(2) DEFAULT 1 DEFAULT NULL COMMENT '状态(1:默认,2:常用)' ,
  `USER_KEY`  INT(11) NOT NULL COMMENT '创建人' ,
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间' ,
  `UPDATE_TIME` DATETIME DEFAULT NOW() COMMENT '最后的更新时间',
  `START_ROW` INT(11) DEFAULT 1 COMMENT '开始解析的行数',
  `START_COLUMN` INT(11) DEFAULT 0 COMMENT '开始解析的列数',
  PRIMARY KEY (`KEY`),
  INDEX INDEX_COMPANY_KEY (`COMPANY_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '企业订单导入模板';


-- 企业订单导入模板明细
DROP TABLE IF EXISTS `T_TEMPLATE_DETAIL`;
CREATE TABLE `T_TEMPLATE_DETAIL` (
  `KEY`  BIGINT(20) NOT NULL COMMENT '模板编号' ,
  `TEMPLATE_KEY` BIGINT(20) NOT NULL COMMENT '模板编号' ,
  `PROPERTY_KEY` BIGINT(20) DEFAULT NULL COMMENT '字段编号(自定义字段为空)' ,
  `POSITION_INDEX`  INT(11) NOT NULL COMMENT '字段位置' ,
  `IS_UNIQUE`  BIT(1) DEFAULT 0 COMMENT '字段是否参与唯一性' ,
  `REQUIRED`  BIT(1) DEFAULT 0 COMMENT '是否必填' ,
  `CUSTOM_NAME`  VARCHAR(50) NOT NULL COMMENT '自定义字段名称' ,
  `DESCRIPTION` VARCHAR(100) DEFAULT NULL COMMENT '自定义描述' ,
  PRIMARY KEY (`KEY`),
  INDEX INDEX_TEMPLATE_KEY (`TEMPLATE_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '企业订单导入模板明细';

-- 订单额外数据
DROP TABLE IF EXISTS `T_ORDER_EXTRA`;
CREATE TABLE `T_ORDER_EXTRA` (
  `KEY` BIGINT(20) NOT NULL COMMENT '订单编号' ,
  `DISTRIBUTE_ADDRESS` VARCHAR(200) DEFAULT NULL COMMENT '发货地址' ,
  `ORIGIN_STATION` VARCHAR(50) DEFAULT NULL COMMENT '始发地' ,
  `ARRIVAL_STATION` VARCHAR(50) DEFAULT NULL COMMENT '目的地' ,
  `START_STATION` VARCHAR(50) DEFAULT NULL COMMENT '发站' ,
  `END_STATION` VARCHAR(50) DEFAULT NULL COMMENT '到站' ,
  `CONVEYER_NAME` VARCHAR(30) DEFAULT NULL COMMENT '承运商联系人' ,
  `CONVEYER_CONTACT` VARCHAR(50) DEFAULT NULL COMMENT '承运商联系电话' ,
  PRIMARY KEY (`KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '订单额外数据';

-- 自定义数据
DROP TABLE IF EXISTS `T_CUSTOM_DATA`;
CREATE TABLE `T_CUSTOM_DATA` (
  `KEY` BIGINT(20) NOT NULL COMMENT '编号' ,
  `DATA_TYPE` INT(11) NOT NULL COMMENT '自定义数据类型(1:订单...)' ,
  `DATA_KEY` VARCHAR(30) NOT NULL COMMENT '数据编号,与数据类型相对应' ,
  `CUSTOM_NAME` VARCHAR(50) DEFAULT NULL COMMENT '自定义数据名称' ,
  `CUSTOM_VALUE` VARCHAR(200) DEFAULT NULL COMMENT '自定义数据值' ,
  PRIMARY KEY (`KEY`),
  INDEX INDEX_DATA_KEY (`DATA_TYPE`, `DATA_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '自定义数据';


-- 订单运输
DROP TABLE IF EXISTS `T_ORDER_CONVEY`;
CREATE TABLE `T_ORDER_CONVEY` (
  `KEY` BIGINT(20) NOT NULL COMMENT '订单编号' ,
  `CARE_NO` VARCHAR(20) NOT NULL COMMENT '车牌号' ,
  `DRIVER_NAME` VARCHAR(30) NOT NULL COMMENT '司机姓名' ,
  `DRIVER_CONTACT` VARCHAR(50) DEFAULT NULL COMMENT '司机联系方式' ,
  PRIMARY KEY (`KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '订单运输';


-- 财务数据
DROP TABLE IF EXISTS `T_FINANCE`;
CREATE TABLE `T_FINANCE` (
  `KEY` BIGINT(20) NOT NULL COMMENT '编号' ,
  `FINANCE_TYPE` INT(11) NOT NULL COMMENT '财务数据类型(1:订单...)' ,
  `OBJECT_KEY` VARCHAR(30) NOT NULL COMMENT '数据编号,与财务数据类型相对应' ,
  `INCOME` DOUBLE DEFAULT 0 COMMENT '收入' ,
  `EXPENDITURE` DOUBLE DEFAULT 0 COMMENT '支出' ,
  `USER_KEY` INT(11) NOT NULL COMMENT '创建人' ,
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '创建时间' ,
  PRIMARY KEY (`KEY`),
  INDEX INDEX_OBJECT_KEY (`FINANCE_TYPE`, `OBJECT_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '财务数据';

INSERT INTO T_SYS_MENU (`ID`, `P_ID`, `MENU_NAME`, `MENU_URL`, `MENU_FETTLE`, `MENU_ICON`, `MENU_TYPE`) VALUES (55, 33, '发货配置', 'enterprise/template/view/manage', 1, NULL, 1);
INSERT INTO T_SYS_ROLE_MENU (`R_ID`, `M_ID`) VALUES ('4', '55');

-- 对外接口配置
DROP TABLE IF EXISTS `T_ADVENTIVE`;
CREATE TABLE `T_ADVENTIVE` (
  `ACCESS_KEY`  BIGINT(20) NOT NULL COMMENT '编号' ,
  `PUBLIC_KEY`  VARCHAR(200) NOT NULL COMMENT '公钥' ,
  `PRIVATE_KEY`  VARCHAR(300) NOT NULL COMMENT '私钥' ,
  `WHITE_LIST`  VARCHAR(200) DEFAULT NULL COMMENT 'IP白名单' ,
  `HIS_CODE`  VARCHAR(20) NOT NULL COMMENT '推送对象代码' ,
  `FREQUENCY`  INT(10) DEFAULT 1 COMMENT '推送频率(秒/次)' ,
  `FREQUENCY_TYPE` INT(10) DEFAULT 1 COMMENT '频率类型(1:正常,2:递增,前三次相同,之后频率越来越慢)' ,
  `MAX_TIMES` INT(10) DEFAULT 10 COMMENT '同一条记录最大推送次数' ,
  `LAST_TIME` DATETIME DEFAULT NOW() COMMENT '最后一次推送的时间' ,
  `FETTLE` INT(11) DEFAULT 1 COMMENT '状态(1:可用,2:不可用)' ,
  `DELIVERY_URL` VARCHAR(300) DEFAULT NULL COMMENT '数据推送URL' ,
  `COMPANY_KEY` BIGINT(20) DEFAULT NULL  COMMENT '关联的企业信息',
  PRIMARY KEY (`ACCESS_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 对外推送记录
DROP TABLE IF EXISTS `T_ADVENTIVE_PUSH`;
CREATE TABLE `T_ADVENTIVE_PUSH` (
  `ADVENTIVE_ID` BIGINT(20) NOT NULL COMMENT '推送对象' ,
  `INCLUDES`  VARCHAR(500) DEFAULT NULL COMMENT '要推送的配置(S发货方编号#R收货方编号#C承运方编号)' ,
  `EXCLUDES`  VARCHAR(500) DEFAULT NULL COMMENT '不推送的配置(S发货方编号#R收货方编号#C承运方编号)' ,
  `DATA_TYPES`  VARCHAR(500) DEFAULT NULL  COMMENT '关注的数据类型',
  PRIMARY KEY (`ADVENTIVE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- 对外推送记录
DROP TABLE IF EXISTS `T_ADVENTIVE_NOTE`;
CREATE TABLE `T_ADVENTIVE_NOTE` (
  `ID` BIGINT(20) NOT NULL COMMENT '编号' ,
  `ADVENTIVE_ID` BIGINT(20) NOT NULL COMMENT '推送对象' ,
  `NOTE_TYPE`  VARCHAR(10) NOT NULL COMMENT '记录类型' ,
  `OBJECT_KEY`  VARCHAR(100) NOT NULL COMMENT '推送的数据编号' ,
  `LAST_TIME`  DATETIME DEFAULT NOW() COMMENT '最后一次推送的时间' ,
  `REMARK`  VARCHAR(200) DEFAULT NULL COMMENT '备注' ,
  `FETTLE` INT(11) DEFAULT 0 COMMENT '状态(0:等待处理,1:处理中,2:处理成功,99:放弃处理)' ,
  `COUNT` INT(11) DEFAULT 0 COMMENT '处理次数' ,
  `OPPOSITE_KEY` VARCHAR(50) DEFAULT NULL  COMMENT '对方的关联编号',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
