
-- 员工客户权限
DROP TABLE IF EXISTS `T_EMPLOYEE_CUSTOMER`;
CREATE TABLE `T_EMPLOYEE_CUSTOMER` (
  `ID` BIGINT(20) NOT NULL COMMENT '编号' ,
  `EMPLOYEE_KEY` INT(11) NOT NULL COMMENT '员工编号' ,
  `CUSTOMER_KEY` BIGINT(20) NOT NULL COMMENT '司机的用户编号' ,
  PRIMARY KEY (`ID`),
  INDEX INDEX_EMPLOYEE_KEY (`EMPLOYEE_KEY`),
  UNIQUE KEY UNIQUE_EKEY_CKEY (`EMPLOYEE_KEY`, `CUSTOMER_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '员工客户权限';


-- 企业客户表新增客户来源
ALTER TABLE `T_COMPANY_CUSTOMER` ADD COLUMN `SOURCE_TYPE` INT(11) DEFAULT 1 COMMENT '来源(1:新建,2:分享,3:指派)';

-- 模板空白列
ALTER TABLE `T_IMPORT_TEMPLATE` ADD COLUMN `EMPTY_COLUMN` VARCHAR(100) DEFAULT NULL COMMENT '空白列(1#2#6#9)';
-- 模板合并的方式
ALTER TABLE `T_IMPORT_TEMPLATE` ADD COLUMN `MERGE_TYPE` INT(11) DEFAULT 0 COMMENT '合并的方式(0:不合并,1:按送货单号合并,2:按收货信息合并)';


-- 订单要求到货时间
ALTER TABLE `T_ORDER` ADD COLUMN `ARRIVAL_TIME` DATETIME DEFAULT NULL COMMENT '要求到货时间';
-- 作废的订单订单要求到货时间
ALTER TABLE `T_ORDER_INVALID` ADD COLUMN `ARRIVAL_TIME` DATETIME DEFAULT NULL COMMENT '要求到货时间';
-- 模板选填字段-要求到货时间
INSERT INTO `T_TEMPLATE_PROPERTY` (`KEY`, `NAME`, `DESCRIPTION`, `CLASS_NAME`, `DATA_KEY`, `DATA_TYPE`, `TYPE`) VALUES ('340391082091520', '要求到货时间', '要求到货时间', 'com.ycg.ksh.service.core.entity.service.enterprise.OrderTemplate', 'arrivalTime', '4', '2');
UPDATE `T_TEMPLATE_PROPERTY` SET DESCRIPTION='下单后生产的订单的编号' WHERE `KEY`=228659327393808;
UPDATE `T_TEMPLATE_PROPERTY` SET TYPE=2 WHERE `KEY`=228659327393792;
UPDATE `T_TEMPLATE_PROPERTY` SET TYPE=2 WHERE `KEY`=228659327393805;

