
-- 用户常用配置
ALTER TABLE `user_commonly` ADD COLUMN `commonly_keys` varchar(255) DEFAULT NULL COMMENT '新版常用功能编号';
ALTER TABLE `user_commonly` ADD COLUMN `driver_commonly_keys` varchar(255) DEFAULT NULL COMMENT '新版司机常用功能编号';
ALTER TABLE `user_commonly` ADD COLUMN `identity_key`  int(11) DEFAULT 2 COMMENT '用户身份标识(1:司机,2:非司机)';

UPDATE `user_commonly` SET `driver_commonly_keys`='203#303#401#602#506#507' , `commonly_keys`='105#201#505#104#204';

-- 系统菜单新增编号
ALTER TABLE `T_SYS_MENU` ADD COLUMN `CODE` VARCHAR(20) DEFAULT NULL COMMENT '菜单编号';

-- 企业名称修改次数
ALTER TABLE `T_COMPANY` ADD COLUMN `RENAME_COUNT` INT(11) DEFAULT 0 COMMENT '企业名称修改次数';


-- 订单表新增数据导入角色
ALTER TABLE `T_ORDER` ADD COLUMN `INSERT_TYPE` INT(11) DEFAULT 1 COMMENT '数据入库方式(1:发货方,2:收货方,3:承运方)';
-- 订单作废表新增数据导入角色
ALTER TABLE `T_ORDER_INVALID` ADD COLUMN `INSERT_TYPE` INT(11) DEFAULT 1 COMMENT '数据入库方式(1:发货方,2:收货方,3:承运方)';


-- alter table T_TEMPLATE_DETAIL alter column IS_UNIQUE set default 1;

-- 订单运输记录
DROP TABLE IF EXISTS `T_ORDER_DELIVER`;
CREATE TABLE `T_ORDER_DELIVER` (
  `ID` BIGINT(20) NOT NULL COMMENT '编号' ,
  `ORDER_KEY` BIGINT(20) NOT NULL COMMENT '订单编号' ,
  `USER_KEY` INT(11) NOT NULL COMMENT '司机的用户编号' ,
  `CREATE_TIME` DATETIME DEFAULT NOW() COMMENT '记录时间' ,
  PRIMARY KEY (`ID`),
  INDEX INDEX_USER_KEY (`USER_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '订单运输记录';

-- 上海金发科技发展有限公司
INSERT INTO `T_COMPANY` (`ID`, `COMPANY_NAME`, `FETTLE`, `SIGN_FETTLE`, `USER_ID`, `CREATE_TIME`, `UPDATE_TIME`, `CODE_ORG`, `CODE_USC`, `LEGAL_NAME`, `LEGAL_ID_NO`, `RENAME_COUNT`) VALUES ('328986561422336', '上海金发科技发展有限公司', '1', '0', '59', '2018-08-22 21:12:41', '2018-08-22 21:12:41', NULL, NULL, NULL, NULL, '0');
INSERT INTO `T_COMPANY_EMPLOYEE` (`COMPANY_ID`, `EMPLOYEE_ID`, `CREATE_TIME`, `USER_ID`, `EMPLOYEE_TYPE`, `EMPLOYEE_NAME`, `USER_FETTLE`) VALUES ('328986561422336', '59', '2018-08-22 16:55:30', '59', '1', '许丛军', '1');
