INSERT INTO `T_SYS_MENU` (`ID`, `P_ID`, `MENU_NAME`, `MENU_URL`, `MENU_FETTLE`, `MENU_ICON`, `MENU_TYPE`, `CODE`) VALUES ('64', '0', '出入库管理', '', '1', 'orderManage', '1', NULL);
INSERT INTO `T_SYS_MENU` (`ID`, `P_ID`, `MENU_NAME`, `MENU_URL`, `MENU_FETTLE`, `MENU_ICON`, `MENU_TYPE`, `CODE`) VALUES ('65', '64', '入库单', 'enterprise/depot/view/order', '1', NULL, '1', NULL);
INSERT INTO `T_SYS_MENU` (`ID`, `P_ID`, `MENU_NAME`, `MENU_URL`, `MENU_FETTLE`, `MENU_ICON`, `MENU_TYPE`, `CODE`) VALUES ('66', '64', '出库批次查询', 'enterprise/depot/view/batch', '1', NULL, '1', NULL);

INSERT INTO `T_SYS_ROLE_MENU` (`R_ID`, `M_ID`) VALUES ('4', '64');
INSERT INTO `T_SYS_ROLE_MENU` (`R_ID`, `M_ID`) VALUES ('4', '65');
INSERT INTO `T_SYS_ROLE_MENU` (`R_ID`, `M_ID`) VALUES ('4', '66');

DROP TABLE IF EXISTS `T_INBOUND_ORDER`;
CREATE TABLE `T_INBOUND_ORDER` (
  `KEY` bigint(20) NOT NULL,
  `BATCH_NUMBER` varchar(50) NOT NULL COMMENT '详细批次',
  `DELIVERY_NO` varchar(20) NOT NULL COMMENT '送货单号',
  `CUSTOMER_ID` bigint(20) NOT NULL COMMENT '客户ID',
  `CUSTOMER_NAME` varchar(50) DEFAULT NULL COMMENT '客户名称',
  `MATERIAL_NAME` varchar(100) DEFAULT NULL COMMENT '物料名称',
  `DELIVERY_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '实际发货日期',
  `PICKING_QUANTITY` int(11) DEFAULT '0' COMMENT '拣配数量',
  `PICKING_NO` varchar(100) DEFAULT NULL COMMENT '物料号',
  `DELIVERY_QUANTITY` int(11) DEFAULT '0' COMMENT '交货数量',
  `LICENSE_PLATE` varchar(50) DEFAULT NULL COMMENT '车牌',
  `STORAGE_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '入库时间',
  `IMPORT_TIMES` int(11) DEFAULT '1' COMMENT '导入次数',
  `OPERATOR_ID` int(11) DEFAULT NULL COMMENT '操作人ID',
  `UPDATE_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `COMPANY_KEY` bigint(20) DEFAULT '0' COMMENT '企业编号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for T_OUTBOUND_DETAILS
-- ----------------------------
DROP TABLE IF EXISTS `T_OUTBOUND_DETAILS`;
CREATE TABLE `T_OUTBOUND_DETAILS` (
  `KEY` bigint(20) DEFAULT NULL,
  `BATCH_NUMBER` varchar(50) DEFAULT NULL COMMENT '批次号',
  `MATERIAL_NAME` varchar(100) DEFAULT NULL COMMENT '品名',
  `OUTBOUND_QUANTITY` int(10) DEFAULT NULL COMMENT '出库数量',
  `OUTBOUND_ID` bigint(20) DEFAULT NULL COMMENT '出库ID',
  `OPERATOR_ID` int(10) DEFAULT NULL COMMENT '操作人ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for T_OUTBOUND_ORDER
-- ----------------------------
DROP TABLE IF EXISTS `T_OUTBOUND_ORDER`;
CREATE TABLE `T_OUTBOUND_ORDER` (
  `KEY` bigint(20) DEFAULT NULL,
  `COMPANY_KEY` bigint(20) DEFAULT '0' COMMENT '企业编号',
  `RECEIVE_ID` bigint(20) DEFAULT NULL COMMENT '收货人ID',
  `SHIPPER_ID` bigint(20) DEFAULT NULL COMMENT '发货人ID',
  `RECEIVE_NAME` varchar(50) DEFAULT NULL COMMENT '收货人名称',
  `SHIPPER_NAME` varchar(50) DEFAULT NULL COMMENT '发货人名称',
  `DELIVERY_NO` varchar(50) DEFAULT NULL COMMENT '送货单号',
  `DELIVERY_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '发货日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;